### ISSUE TITLE
The range of the hoving zone is incomple.

### ISSUE THREAD

**Issue by xhuajin** [KuiyueRO/Obsidian-Miner#5]
I use Miner.CSS and find something that can improve. When the mouse cursor is at the very top of the file tree ( The place that contain "Files", "Search" and "Bookmarks"), it will end hoving if the cursor do not actually touching the icon. So when i move from the file tree to the top to reach the "Search" bottom, it will stop hoving. My skill level is very limited and I can't solve this problem for the time being. Would you be interested in improving it in your spare time. Thank you very much.

**Comment by KuiyueRO** [comment]
你说的是Float_Sidebar CSS片段吗

**Comment by KuiyueRO** [comment]
这个周末修一下，还有不少样式要一同改。

![image](https://github.com/KuiyueRO/Obsidian-Miner/assets/63145205/539dc44f-922e-47a8-9340-5967a6241af3)

![image](https://github.com/KuiyueRO/Obsidian-Miner/assets/63145205/16767a7e-4138-4b19-97f5-3955b69313d3)

**Comment by xhuajin** [comment]
非常感谢，修复了一定来下载！

**Comment by KuiyueRO** [comment]
[v0.0.6](https://github.com/KuiyueRO/Obsidian-Miner/releases/tag/v0.0.6)
