### ISSUE TITLE
右上角图标堆叠

### ISSUE THREAD

**Issue by xhuajin** [KuiyueRO/Obsidian-Miner#6]
在Miner_Float_Sidebar.css中，.workspace-tab-header-container-inner的overflow被设置为了visible，然后我的右上角的图标会和关闭obsidian的那三个图标堆叠在一起，我改成auto就恢复正常了。我想问问改成auto会造成其他什么影响吗（暂未发现）

**Comment by KuiyueRO** [comment]
如果没影响的话，那就是没影响了，这可能是之前我将关闭这三个按钮移动到左边时遗留的，忘记清理了，时间久远，已经记不清了。感谢提醒。

**Comment by xhuajin** [comment]
这个css好好看，非常感谢你！

**Comment by KuiyueRO** [comment]
谢谢!!!
